# Generated by Django 4.2.5 on 2023-12-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_updater",
            field=models.BooleanField(default=False),
        ),
    ]
