# Generated by Django 4.2.5 on 2023-12-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_updater'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_controller',
            field=models.BooleanField(default=False, verbose_name='Controller Status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_updater',
            field=models.BooleanField(default=False, verbose_name='Updater Status'),
        ),
    ]
